register.service:
  # Registration service type, supported SERVICE_COMB/NACOS
  registerType: SERVICE_COMB
  # Registration service address，service_comb：http://localhost:30100；nacos：127.0.0.1:8848
  address: http://localhost:30100
  # If SSL is enabled, the instance protocol is https for Service Discovery when secure is true,
  # the instance protocol is http for Service Discovery when secure is false
  secure: false
servicecomb.service:
  # Heartbeat sending interval of a service instance (unit: seconds)
  heartbeatInterval: 15
  # Specifies whether to enable the migration feature
  openMigration: false
  # Specifies whether to enable the Spring plug-in registration capability
  enableSpringRegister: false
  # Specifies whether to enable the dubbo plug-in registration capability
  enableDubboRegister: false
  # Specifies whether SSL is enabled
  sslEnabled: false
  # If true, the IP address access method is used instead of the domain name
  preferIpAddress: false
grace.rule:
  # springCloud elegant on-line and off-line switches
  enableSpring: false
  # Elegant up/down line start-up delay time, in S
  startDelayTime: 0
  # Specifies whether to enable preheating
  enableWarmUp: false
  # Warm-up time, in S
  warmUpTime: 120
  # Whether to enable elegant offline
  enableGraceShutdown: false
  # The maximum wait time for correlation traffic detection before closing,
  # in S. enabledGraceShutdown must be enabled for it to take effect
  shutdownWaitTime: 30
  # Is offline active notification enabled
  enableOfflineNotify: false
  # HTTP Server port when enabling active offline notifications
  httpServerPort: 16688
  # The default size of the cache upstream address
  upstreamAddressMaxSize: 500
  # The expiration time of the upstream address of the cache
  upstreamAddressExpiredTime: 60
nacos.service:
  # Nacos verification Account
  username: ""
  # Nacos verification password
  password: ""
  # Namespace，The ID value of the namespace created by Nacos is configured
  namespace: ""
  # The weight value of the service instance
  weight: 1
  # The name of the cluster
  clusterName: DEFAULT
  # Whether it is a temporary node，True is yes, false is no
  ephemeral: true
remove.bean:
  autoName: "wiki.xsx.core.config.ConsulRetryAutoConfiguration,com.volvo.retry.config.ConsulRetryAutoConfiguration"
  componentName: "com.volvo.cms.customer.ZookeeperEventListener,com.volvo.retry.config.ConsulRetryAutoConfiguration"