# consul发现配置
sermant.discovery.realm:
  currentRealmName: gateway.t3go.com.cn

sermant.discovery.lb:
  lbType: RoundRobin               # 负载均衡类型, 当前支持轮询(RoundRobin)、随机(Random)、响应时间权重(WeightedResponseTime)、最低并发数(BestAvailable)
  registryAddress: 127.0.0.1:2181  # 注册中心地址
