server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.opengauss.Driver
    url: jdbc:opengauss://127.0.0.1:5432/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username:
    password:
  application:
    name: opengauss-demo